// Code generated by Slice Machine. DO NOT EDIT.

import Concert from './Concert';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';
import Welcome from './Welcome';

export {
	Concert,
	ContactForm,
	Image,
	Quote,
	Text,
	Welcome,
};

export const components = {
	concert: Concert,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
	welcome: Welcome,
};
